api_key:
api_base:
model: gpt-4-turbo
temperature: 0
simulator_seed: 42
tools_folder: "./tools"
cache_folder: "./tool_response_cache"
generated_cache_folder: "../data/generated_cache/solvable_v1/responses"
port: 8080
log_file: "./server.log"
qos_enabled: false
qos_profiles_file: "../data/qos/v5/api_qos_profiles.jsonl"
qos_profile: "normal"
qos_seed: 42
qos_sleep_enabled: true
